// <auto-generated />
using System;
using DSEV.Schemas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DSEV.Migrations.캘리브테이블Migrations
{
    [DbContext(typeof(캘리브테이블))]
    partial class 캘리브테이블ModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DSEV.Schemas.캘리브정보", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnName("ctime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("AngleB")
                        .HasColumnName("cangb")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AngleL")
                        .HasColumnName("cangl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AngleR")
                        .HasColumnName("cangr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AngleT")
                        .HasColumnName("cangt")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalibX")
                        .HasColumnName("ccalx")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CalibY")
                        .HasColumnName("ccaly")
                        .HasColumnType("numeric");

                    b.Property<int>("Camera")
                        .HasColumnName("ccame")
                        .HasColumnType("integer");

                    b.Property<decimal>("Height")
                        .HasColumnName("cheig")
                        .HasColumnType("numeric");

                    b.Property<int>("Index")
                        .HasColumnName("cindx")
                        .HasColumnType("integer");

                    b.Property<decimal>("LengthB")
                        .HasColumnName("clenb")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LengthL")
                        .HasColumnName("clenl")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LengthR")
                        .HasColumnName("clenr")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LengthT")
                        .HasColumnName("clent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Width")
                        .HasColumnName("cwidt")
                        .HasColumnType("numeric");

                    b.HasKey("Time");

                    b.ToTable("calibs");
                });
#pragma warning restore 612, 618
        }
    }
}
